common_config:
  proc: [1, 2, 3, 4]
  memory_limit: 4000
  time_limit: 360
  tags: [benchmark]


test_cases:
- files:
  - flow_bddc_fieldformula.yaml
  - flow_bddc.yaml
  - flow_dg_sorption.yaml
  - flow_fv_sorption.yaml
  - flow_fv.yaml
  - flow_LMH_dg_heat.yaml
  - flow_LMH_richards.yaml
  - flow_unsteady_dg.yaml
  proc:     [1]
  inputs:   [1_15786_el]
  tags:     [benchmark, weak-scale]
  
- files:
  - flow_bddc_fieldformula.yaml
  - flow_bddc.yaml
  - flow_dg_sorption.yaml
  - flow_fv_sorption.yaml
  - flow_fv.yaml
  - flow_LMH_dg_heat.yaml
  - flow_LMH_richards.yaml
  - flow_unsteady_dg.yaml
  proc:     [2]
  inputs:   [2_29365_el]
  tags:     [benchmark, weak-scale]
  
- files:
  - flow_bddc_fieldformula.yaml
  - flow_bddc.yaml
  - flow_dg_sorption.yaml
  - flow_fv_sorption.yaml
  - flow_fv.yaml
  - flow_LMH_dg_heat.yaml
  - flow_LMH_richards.yaml
  - flow_unsteady_dg.yaml
  proc:     [3]
  inputs:   [3_47367_el]
  tags:     [benchmark, weak-scale]
  
- files:
  - flow_bddc_fieldformula.yaml
  - flow_bddc.yaml
  - flow_dg_sorption.yaml
  - flow_fv_sorption.yaml
  - flow_fv.yaml
  - flow_LMH_dg_heat.yaml
  - flow_LMH_richards.yaml
  - flow_unsteady_dg.yaml
  proc:     [4]
  inputs:   [4_58803_el]
  tags:     [benchmark, weak-scale]
  
  # - 1_15786_el
  # - 2_29365_el
  # - 3_47367_el
  # - 4_58803_el
  # - 5_78379_el
  # - 6_89683_el
  # - 7_104912_el
  # - 8_118696_el
  # - 9_139280_el
  # - 10_152389_el
  # - 11_165361_el
  # - 12_183061_el
  # - 13_197786_el
  # - 14_211246_el
  # - 15_233079_el
  # - 16_261685_el


